name: learn_dart
description: Learning Dart with Pete Houston.
version: 1.0.0
homepage: https://petehouston.com
author: Pete Houston <contact@petehouston.com>

environment:
  sdk: '>=2.1.0 <3.0.0'

#dependencies:
#  path: ^1.4.1

dev_dependencies:
  test: ^1.0.0
